version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gym_crm_db
      MYSQL_USER: my_username
      MYSQL_PASSWORD: my_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: