version: '3.8'

services:
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: gym_crm_db
            MYSQL_USER: my_username
            MYSQL_PASSWORD: my_password
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - backend

    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        networks:
            - backend

    activemq:
        image: apache/activemq-artemis:latest
        container_name: activemq
        ports:
            - "8161:8161" # Web Console
            - "61616:61616" # JMS
        environment:
            - ARTEMIS_USER=admin
            - ARTEMIS_PASSWORD=admin
        volumes:
            - artemis-data:/var/lib/artemis/data
            - artemis-etc:/var/lib/artemis/etc
        networks:
            - backend

    gym-service:
        container_name: gym-service
        build:
            context: ./gym-service
            dockerfile: Dockerfile
            args:
                GYM_SERVICE_PORT: ${GYM_SERVICE_PORT}
        ports:
            - "8080:8080"
        env_file:
            - .env
        networks:
            - backend2
        depends_on:
            - mysql

    trainings-report-service:
        container_name: trainings-report-service
        build:
            context: ./trainings-report-service
            dockerfile: Dockerfile
            args:
                TRAININGS_REPORT_SERVICE_PORT: ${TRAININGS_REPORT_SERVICE_PORT}
        ports:
            - "8082:8082"
        env_file:
            - .env
        networks:
            - backend3

volumes:
    mysql_data:
    artemis-data:
    artemis-etc:

networks:
    backend:
    backend2:
    backend3: