datasource:
  url: jdbc:mysql://localhost:3306/gym_crm_db
  username: my_username
  password: my_password
  hibernate:
    show_sql: true
    dialect: org.hibernate.dialect.MySQLDialect

jwt:
  key: secret_key
  exp: 3600
