spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: my_username
    password: my_password
  jpa:
    show_sql: true
  liquibase:
    change-log: changelog/changelog.xml

jwt:
  key: secret_key
  exp: 3600

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true