spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_crm_db
    username: my_username
    password: my_password
  jpa:
    show_sql: true
  liquibase:
    change-log: db/changelog/changelog.xml

jwt:
  key: secret_key
  exp: 3600

cors:
    urls: http://localhost:8081

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true