server:
    port: ${TRAININGS_REPORT_SERVICE_PORT:8082}

spring:
    data:
        mongodb:
            database: ${MONGO_DB:mongo_db}
            auto-index-creation: true
    mongodb:
        embedded:
            version: 4.12.6
    activemq:
        broker-url: ${ACTIVEMQ_URL:tcp://localhost:61616}
        user: ${ACTIVEMQ_USERNAME:admin}
        password: ${ACTIVEMQ_PASSWORD:admin}
        client-id: ${CONSUMER_ID:consumer1}
        topic-name: ${TRAINER_WORKLOAD_TOPIC_NAME:trainer.workload}

de:
    flapdoodle:
        mongodb:
            embedded:
                version: 7.3.0

jwt:
    key: secret_key
    exp: 3600