server:
    port: 8082

spring:
    application:
        name: trainings-report-service
    data:
        mongodb:
            database: mongo_db
    mongodb:
        embedded:
            version: 4.12.6

de:
    flapdoodle:
        mongodb:
            embedded:
                version: 7.3.0

eureka:
    client:
        register-with-eureka: true
        service-url:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

jwt:
    key: secret_key
    exp: 3600